#!/usr/bin/env python3
"""Build a corpus from the VMware Cloud Foundation 9.1 documentation PDF.

    python3 vcf_fetch.py                    # extract, section, write the corpus
    python3 vcf_fetch.py --reuse-text       # skip extraction, reuse the cache
    python3 vcf_fetch.py --pdf other.pdf    # a different DITA generated PDF

One local file, no network at all. The PDF is 8,894 pages and 182 MB, which is
the interesting part: it is far too large to put in a prompt, and far too
uniform to chunk blindly. Every page carries the same running header, the same
footer, and the same product name, so a fixed size chunker produces thousands of
passages that all look alike to a retriever and none of which say where they
came from.

**The structure is already in the document, so it is used rather than guessed.**
The file was generated by DITA Open Toolkit, which means a real table of
contents with dot leaders, page numbers, and indentation that encodes nesting
depth. Parsing that gives 3,289 sections with genuine titles and a breadcrumb
path, so a retrieved passage can say "Deployment > VCF Installer > Deploy a VCF
Instance" instead of "chunk 4,412".

Two extractions, because one pass cannot give both:

    pdftotext            reflowed prose, which is what should be indexed
    pdftotext -layout    preserves leading whitespace, which is the only place
                         the table of contents records nesting depth

The default reflow flattens every entry to the left margin, so the hierarchy is
present in the PDF and absent from the text unless -layout is asked for. It is
asked for over the contents pages only, since -layout makes body prose worse by
preserving column artefacts.

Requires poppler for pdftotext:

    brew install poppler

Page numbers printed in the contents match 1 based PDF page numbers in this
document, verified rather than assumed: the contents say Release Notes is on 79
and PDF page 79 begins "Release Notes". A document where those disagree needs
--page-offset.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CORPUS = os.path.join(HERE, "corpus")
RAW = os.path.join(CORPUS, "raw", "vcf91")
OUT = os.path.join(CORPUS, "vcf91.jsonl")
PDF = os.path.join(HERE, "vcf91", "vmware-cloud-foundation-9-1.pdf")

# Lines repeated on almost every page. They carry no retrieval signal and, worse,
# they are identical across 8,894 pages, so leaving them in gives every chunk the
# same handful of terms and flattens the differences a retriever scores on.
FURNITURE = re.compile(
    r"^(VMware Cloud Foundation 9\.\d+|VMware by Broadcom|\d{1,4})\s*$", re.M
)

# A contents line: indentation, a title, dot leaders, a page number.
TOC_LINE = re.compile(r"^(\s*)(\S.*?)\.{3,}\s*(\d+)\s*$", re.M)

# Indentation widths cluster rather than falling on exact multiples, because the
# generator positions text by point size and not by character count. Observed
# clusters in this document are 0, 3, 8-11 and 13-18, so the buckets are drawn
# between the clusters instead of at arithmetic multiples of some indent unit.
DEPTH_BUCKETS = [(2, 0), (7, 1), (13, 2)]


def depth_of(indent: int) -> int:
    for width, level in DEPTH_BUCKETS:
        if indent < width:
            return level
    return 3


def run(args: list[str]) -> str:
    result = subprocess.run(args, capture_output=True, text=True)
    if result.returncode != 0:
        raise SystemExit(f"{args[0]} failed: {result.stderr.strip()}")
    return result.stdout


def page_count(pdf: str) -> int:
    for line in run(["pdfinfo", pdf]).splitlines():
        if line.startswith("Pages:"):
            return int(line.split(":", 1)[1])
    raise SystemExit("pdfinfo did not report a page count")


def extract(pdf: str, reuse: bool) -> tuple[str, str]:
    """Reflowed body text, and layout preserved contents pages."""
    os.makedirs(RAW, exist_ok=True)
    body_path = os.path.join(RAW, "vcf91.txt")
    toc_path = os.path.join(RAW, "toc-layout.txt")

    if not (reuse and os.path.exists(body_path) and os.path.exists(toc_path)):
        print("extracting  this takes a couple of minutes on 8,894 pages")
        run(["pdftotext", "-enc", "UTF-8", pdf, body_path])
        run(["pdftotext", "-enc", "UTF-8", "-layout", "-f", "1", "-l", "78",
             pdf, toc_path])

    body = open(body_path, encoding="utf-8", errors="replace").read()
    toc = open(toc_path, encoding="utf-8", errors="replace").read()

    # The count is checked because a partial extraction looks exactly like a
    # complete one: pdftotext returns 0, writes nothing to stderr, and leaves a
    # file that reads perfectly up to the point where it stops.
    pages = body.split("\f")
    expected = page_count(pdf)
    if len(pages) < expected:
        raise SystemExit(
            f"extracted {len(pages)} pages of an expected {expected}.\n"
            "  The text file is incomplete. Delete corpus/raw/vcf91/ and retry.")
    return body, toc


def parse_toc(toc: str, first_body_page: int) -> list[dict]:
    entries = []
    for indent, title, page in TOC_LINE.findall(toc):
        page = int(page)
        if page < first_body_page:
            continue  # a contents line pointing inside the contents itself
        entries.append({
            "title": " ".join(title.split()),
            "page": page,
            "depth": depth_of(len(indent)),
        })
    entries.sort(key=lambda e: e["page"])
    return entries


def breadcrumb(entries: list[dict], i: int) -> str:
    """The path of ancestors above entry i, nearest last."""
    trail, want = [], entries[i]["depth"] - 1
    for j in range(i - 1, -1, -1):
        if want < 0:
            break
        if entries[j]["depth"] == want:
            trail.append(entries[j]["title"])
            want -= 1
    return " > ".join(reversed(trail))


# A section is cut short at the next section's title, which fails on the landing
# pages: those carry a navigation list of the child headings before any prose, so
# the first occurrence of the next title is a link and not the heading it names.
# "Upgrade Sequence to 9.1" was lost exactly this way. Its span began on page 79,
# the list of siblings on that page put "What's New" 24 characters in, the cut
# fired there, and the section was reduced to its own heading and dropped for
# having no prose under it. The next title is only accepted as a boundary when
# it leaves a section worth keeping; otherwise a later occurrence is tried, and
# if none qualifies the span simply runs to the page boundary. A section that
# runs slightly long costs a little retrieval precision. A section that vanishes
# cannot be retrieved at all.
MIN_KEEP = 200


def next_heading(span: str, title: str, start: int) -> int:
    at = span.find(title, start)
    while 0 < at < MIN_KEEP:
        at = span.find(title, at + len(title))
    return at


def clean(text: str) -> str:
    text = FURNITURE.sub("", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def sections(body: str, entries: list[dict]) -> list[dict]:
    """Slice the body at each section title, falling back to page boundaries.

    Several sections can begin on one page, so slicing by page alone would give
    the second and third of them nothing. The title is looked for inside the
    page it is declared on, and the cut is made there when it is found. When it
    is not - a title broken across lines, or rewritten in the contents - the
    page boundary is used and the section simply starts a little early. That
    degrades a citation; it does not lose text.
    """
    pages = body.split("\f")
    out = []
    for i, entry in enumerate(entries):
        start_page = entry["page"] - 1
        end_page = entries[i + 1]["page"] - 1 if i + 1 < len(entries) else len(pages)
        if start_page >= len(pages):
            continue

        span = "\f".join(pages[start_page:max(end_page + 1, start_page + 1)])

        # Cut at this title, and again at the next one if it shares the span.
        head = span.find(entry["title"])
        if head > 0:
            span = span[head:]
        if i + 1 < len(entries):
            nxt = next_heading(span, entries[i + 1]["title"], len(entry["title"]))
            if nxt > 0:
                span = span[:nxt]

        trail = breadcrumb(entries, i) or "VMware Cloud Foundation 9.1"
        for part in split_pages(span, entry["page"]):
            text = clean(part["text"])
            if len(text) < 40:
                continue  # a heading with no prose under it, which is a link page
            out.append({
                "citation": entry["title"][:60],
                "section": entry["title"],
                "chapter_name": trail,
                "url": f"vcf91/vmware-cloud-foundation-9-1.pdf#page={part['page']}",
                "text": text,
            })
    return out


# Sections run from one contents entry to the next, and a few headings have no
# sub-entries listed under them at all: "VCF SDKs, APIs, and CLIs" covers pages
# 111 to 501 as a single span of 785,000 characters. Left whole, every chunk cut
# from it would cite page 111 no matter which of those 390 pages it came from,
# which is a citation that points at the right book and the wrong place. Page
# boundaries are already known here, so an oversized span is broken on them and
# each piece keeps the page it actually starts on.
MAX_SPAN = 20_000
TARGET_SPAN = 8_000


def split_pages(span: str, first_page: int) -> list[dict]:
    pages = span.split("\f")
    if len(span) <= MAX_SPAN or len(pages) < 2:
        return [{"text": span.replace("\f", "\n"), "page": first_page}]

    parts, buffer, start = [], [], first_page
    for offset, page in enumerate(pages):
        buffer.append(page)
        if sum(len(p) for p in buffer) >= TARGET_SPAN:
            parts.append({"text": "\n".join(buffer), "page": start})
            buffer, start = [], first_page + offset + 1
    if buffer:
        parts.append({"text": "\n".join(buffer), "page": start})
    return parts


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--pdf", default=PDF)
    ap.add_argument("--out", default=OUT)
    ap.add_argument("--reuse-text", action="store_true",
                    help="reuse the cached extraction under corpus/raw/vcf91/")
    ap.add_argument("--first-body-page", type=int, default=79,
                    help="first page after the table of contents")
    args = ap.parse_args()

    if not os.path.exists(args.pdf):
        raise SystemExit(f"no PDF at {args.pdf}")
    if not shutil_which("pdftotext"):
        raise SystemExit("pdftotext is not installed.\n  brew install poppler")

    body, toc = extract(args.pdf, args.reuse_text)
    entries = parse_toc(toc, args.first_body_page)
    if not entries:
        raise SystemExit(
            "no contents entries found.\n"
            "  This parser expects dot leaders, as DITA Open Toolkit emits.")

    records = sections(body, entries)
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        for record in records:
            fh.write(json.dumps(record, ensure_ascii=False) + "\n")

    chars = sum(len(r["text"]) for r in records)
    print(f"pdf       {page_count(args.pdf):,} pages")
    print(f"contents  {len(entries):,} entries, {len(records):,} with prose under them")
    print(f"corpus    {chars:,} chars -> {args.out}")
    print()
    print("Next, and note the backend and the chunk size:")
    print("  python3 rag_index.py --backend mlx --max-chars 20000 --overlap 0 \\")
    print(f"                       --corpus {args.out} \\")
    print("                       --index corpus/vcf91.db")
    print()
    print("  --backend mlx reads 8192 tokens, and the longest section here is")
    print("  about 5,000, so every section is indexed whole and no citation")
    print("  points at a fragment. --backend st reads 256 and needs chunking.")
    print("  bm25 cannot index this corpus at all: it stores one dense row per")
    print("  chunk across the whole vocabulary, which runs to gigabytes here.")


def shutil_which(name: str) -> str | None:
    import shutil
    return shutil.which(name)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(130)
